# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l8_lst_swa_main_ui.ui'
#
# Created: Wed Jan 27 06:50:45 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(399, 459)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Landsat8LST_SWA/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.runButton = QtGui.QPushButton(Dialog)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout.addWidget(self.runButton, 3, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 3, 1, 1, 1)
        self.closeButton = QtGui.QPushButton(Dialog)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout.addWidget(self.closeButton, 3, 2, 1, 1)
        self.processLabel = QtGui.QLabel(Dialog)
        self.processLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.processLabel.setObjectName(_fromUtf8("processLabel"))
        self.gridLayout.addWidget(self.processLabel, 2, 1, 1, 1)
        self.helpButton = QtGui.QPushButton(Dialog)
        self.helpButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Landsat8LST_SWA/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon1)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.gridLayout.addWidget(self.helpButton, 3, 0, 1, 1)
        self.statusGroupBox = QtGui.QGroupBox(Dialog)
        self.statusGroupBox.setObjectName(_fromUtf8("statusGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.statusGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.statusSatelliteCheckBox = QtGui.QCheckBox(self.statusGroupBox)
        self.statusSatelliteCheckBox.setEnabled(False)
        self.statusSatelliteCheckBox.setObjectName(_fromUtf8("statusSatelliteCheckBox"))
        self.horizontalLayout.addWidget(self.statusSatelliteCheckBox)
        self.statusMeteoCheckBox = QtGui.QCheckBox(self.statusGroupBox)
        self.statusMeteoCheckBox.setEnabled(False)
        self.statusMeteoCheckBox.setObjectName(_fromUtf8("statusMeteoCheckBox"))
        self.horizontalLayout.addWidget(self.statusMeteoCheckBox)
        self.statusGroundCheckBox = QtGui.QCheckBox(self.statusGroupBox)
        self.statusGroundCheckBox.setEnabled(False)
        self.statusGroundCheckBox.setObjectName(_fromUtf8("statusGroundCheckBox"))
        self.horizontalLayout.addWidget(self.statusGroundCheckBox)
        self.statusOutputCheckBox = QtGui.QCheckBox(self.statusGroupBox)
        self.statusOutputCheckBox.setEnabled(False)
        self.statusOutputCheckBox.setObjectName(_fromUtf8("statusOutputCheckBox"))
        self.horizontalLayout.addWidget(self.statusOutputCheckBox)
        self.gridLayout.addWidget(self.statusGroupBox, 1, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.satTabDataGroupBox = QtGui.QGroupBox(self.tab)
        self.satTabDataGroupBox.setObjectName(_fromUtf8("satTabDataGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.satTabDataGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.satTabDataTypeRawRadioButton = QtGui.QRadioButton(self.satTabDataGroupBox)
        self.satTabDataTypeRawRadioButton.setChecked(True)
        self.satTabDataTypeRawRadioButton.setObjectName(_fromUtf8("satTabDataTypeRawRadioButton"))
        self.horizontalLayout_2.addWidget(self.satTabDataTypeRawRadioButton)
        self.satTabCorrectedRadioButton = QtGui.QRadioButton(self.satTabDataGroupBox)
        self.satTabCorrectedRadioButton.setObjectName(_fromUtf8("satTabCorrectedRadioButton"))
        self.horizontalLayout_2.addWidget(self.satTabCorrectedRadioButton)
        self.gridLayout_5.addWidget(self.satTabDataGroupBox, 0, 0, 1, 1)
        self.satTabToolBox = QtGui.QToolBox(self.tab)
        self.satTabToolBox.setEnabled(True)
        self.satTabToolBox.setObjectName(_fromUtf8("satTabToolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 357, 182))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.satTabRawCheckButton = QtGui.QPushButton(self.page)
        self.satTabRawCheckButton.setObjectName(_fromUtf8("satTabRawCheckButton"))
        self.gridLayout_3.addWidget(self.satTabRawCheckButton, 2, 0, 1, 1)
        self.satTabMTLAddButton = QtGui.QPushButton(self.page)
        self.satTabMTLAddButton.setObjectName(_fromUtf8("satTabMTLAddButton"))
        self.gridLayout_3.addWidget(self.satTabMTLAddButton, 0, 0, 1, 1)
        self.satTabMTLPathLine = QtGui.QLineEdit(self.page)
        self.satTabMTLPathLine.setReadOnly(True)
        self.satTabMTLPathLine.setObjectName(_fromUtf8("satTabMTLPathLine"))
        self.gridLayout_3.addWidget(self.satTabMTLPathLine, 0, 1, 1, 1)
        self.satTabToolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 222, 145))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.satTabB11ComboBox = QtGui.QComboBox(self.page_2)
        self.satTabB11ComboBox.setObjectName(_fromUtf8("satTabB11ComboBox"))
        self.gridLayout_4.addWidget(self.satTabB11ComboBox, 1, 1, 1, 1)
        self.satTabB10ComboBox = QtGui.QComboBox(self.page_2)
        self.satTabB10ComboBox.setObjectName(_fromUtf8("satTabB10ComboBox"))
        self.gridLayout_4.addWidget(self.satTabB10ComboBox, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.satTabNDVIComboBox = QtGui.QComboBox(self.page_2)
        self.satTabNDVIComboBox.setObjectName(_fromUtf8("satTabNDVIComboBox"))
        self.gridLayout_4.addWidget(self.satTabNDVIComboBox, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.satTabCorrectedCheckButton = QtGui.QPushButton(self.page_2)
        self.satTabCorrectedCheckButton.setObjectName(_fromUtf8("satTabCorrectedCheckButton"))
        self.gridLayout_4.addWidget(self.satTabCorrectedCheckButton, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 4, 0, 1, 1)
        self.satTabAqDateTime = QtGui.QDateEdit(self.page_2)
        self.satTabAqDateTime.setCalendarPopup(True)
        self.satTabAqDateTime.setObjectName(_fromUtf8("satTabAqDateTime"))
        self.gridLayout_4.addWidget(self.satTabAqDateTime, 4, 1, 1, 1)
        self.satTabToolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.satTabToolBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.waterVaporGroupBox = QtGui.QGroupBox(self.tab_2)
        self.waterVaporGroupBox.setObjectName(_fromUtf8("waterVaporGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.waterVaporGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.waterVaporMODISRadioButton = QtGui.QRadioButton(self.waterVaporGroupBox)
        self.waterVaporMODISRadioButton.setObjectName(_fromUtf8("waterVaporMODISRadioButton"))
        self.gridLayout_8.addWidget(self.waterVaporMODISRadioButton, 3, 0, 1, 1)
        self.waterVaporMODISSettings = QtGui.QPushButton(self.waterVaporGroupBox)
        self.waterVaporMODISSettings.setObjectName(_fromUtf8("waterVaporMODISSettings"))
        self.gridLayout_8.addWidget(self.waterVaporMODISSettings, 3, 1, 1, 1)
        self.waterVaporMeanRadioButtonLine = QtGui.QLineEdit(self.waterVaporGroupBox)
        self.waterVaporMeanRadioButtonLine.setObjectName(_fromUtf8("waterVaporMeanRadioButtonLine"))
        self.gridLayout_8.addWidget(self.waterVaporMeanRadioButtonLine, 0, 1, 1, 1)
        self.waterVaporGRIDRadioButton = QtGui.QRadioButton(self.waterVaporGroupBox)
        self.waterVaporGRIDRadioButton.setObjectName(_fromUtf8("waterVaporGRIDRadioButton"))
        self.gridLayout_8.addWidget(self.waterVaporGRIDRadioButton, 1, 0, 1, 1)
        self.waterVaporMeanRadioButton = QtGui.QRadioButton(self.waterVaporGroupBox)
        self.waterVaporMeanRadioButton.setChecked(True)
        self.waterVaporMeanRadioButton.setObjectName(_fromUtf8("waterVaporMeanRadioButton"))
        self.gridLayout_8.addWidget(self.waterVaporMeanRadioButton, 0, 0, 1, 1)
        self.waterVaporGRIDComboBox = QtGui.QComboBox(self.waterVaporGroupBox)
        self.waterVaporGRIDComboBox.setObjectName(_fromUtf8("waterVaporGRIDComboBox"))
        self.gridLayout_8.addWidget(self.waterVaporGRIDComboBox, 1, 1, 1, 1)
        self.waterVaporCheckButton = QtGui.QPushButton(self.waterVaporGroupBox)
        self.waterVaporCheckButton.setObjectName(_fromUtf8("waterVaporCheckButton"))
        self.gridLayout_8.addWidget(self.waterVaporCheckButton, 4, 1, 1, 1)
        self.gridLayout_9.addWidget(self.waterVaporGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.LSEGRIDRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.LSEGRIDRadioButton.setObjectName(_fromUtf8("LSEGRIDRadioButton"))
        self.gridLayout_7.addWidget(self.LSEGRIDRadioButton, 2, 0, 1, 1)
        self.LSENDVIRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.LSENDVIRadioButton.setChecked(True)
        self.LSENDVIRadioButton.setObjectName(_fromUtf8("LSENDVIRadioButton"))
        self.gridLayout_7.addWidget(self.LSENDVIRadioButton, 0, 0, 1, 1)
        self.LSECheckButton = QtGui.QPushButton(self.groupBox_3)
        self.LSECheckButton.setObjectName(_fromUtf8("LSECheckButton"))
        self.gridLayout_7.addWidget(self.LSECheckButton, 3, 1, 1, 1)
        self.LSEGRIDComboBox = QtGui.QComboBox(self.groupBox_3)
        self.LSEGRIDComboBox.setObjectName(_fromUtf8("LSEGRIDComboBox"))
        self.gridLayout_7.addWidget(self.LSEGRIDComboBox, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.outputLSTLine = QtGui.QLineEdit(self.tab_5)
        self.outputLSTLine.setReadOnly(True)
        self.outputLSTLine.setObjectName(_fromUtf8("outputLSTLine"))
        self.gridLayout_10.addWidget(self.outputLSTLine, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_10.addWidget(self.label_3, 1, 0, 1, 1)
        self.outputLSTBrowseButton = QtGui.QPushButton(self.tab_5)
        self.outputLSTBrowseButton.setObjectName(_fromUtf8("outputLSTBrowseButton"))
        self.gridLayout_10.addWidget(self.outputLSTBrowseButton, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 7, 1, 1, 1)
        self.outputLSTCheckButton = QtGui.QPushButton(self.tab_5)
        self.outputLSTCheckButton.setObjectName(_fromUtf8("outputLSTCheckButton"))
        self.gridLayout_10.addWidget(self.outputLSTCheckButton, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 5, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 6, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 4)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.satTabToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Landsat 8 LST Retriever (SWA)", None))
        self.runButton.setText(_translate("Dialog", "Run", None))
        self.closeButton.setText(_translate("Dialog", "Close", None))
        self.processLabel.setText(_translate("Dialog", "No active processes", None))
        self.statusGroupBox.setTitle(_translate("Dialog", "Status", None))
        self.statusSatelliteCheckBox.setText(_translate("Dialog", "Satellite data", None))
        self.statusMeteoCheckBox.setText(_translate("Dialog", "Meteorological data", None))
        self.statusGroundCheckBox.setText(_translate("Dialog", "Ground data", None))
        self.statusOutputCheckBox.setText(_translate("Dialog", "Output", None))
        self.satTabDataGroupBox.setTitle(_translate("Dialog", "Data type", None))
        self.satTabDataTypeRawRadioButton.setText(_translate("Dialog", "Raw Landsat 8 data (MTL.txt)", None))
        self.satTabCorrectedRadioButton.setText(_translate("Dialog", "Corrected Landsat 8 data", None))
        self.satTabRawCheckButton.setText(_translate("Dialog", "Check", None))
        self.satTabMTLAddButton.setText(_translate("Dialog", "Add from MTL.txt", None))
        self.satTabToolBox.setItemText(self.satTabToolBox.indexOf(self.page), _translate("Dialog", "Raw Landsat 8 data", None))
        self.label_12.setText(_translate("Dialog", "B10 mono-channel layer", None))
        self.label_13.setText(_translate("Dialog", "NDVI layer", None))
        self.label_16.setText(_translate("Dialog", "B11 mono-channel layer", None))
        self.satTabCorrectedCheckButton.setText(_translate("Dialog", "Check", None))
        self.label_2.setText(_translate("Dialog", "Aquisition date", None))
        self.satTabToolBox.setItemText(self.satTabToolBox.indexOf(self.page_2), _translate("Dialog", "Corrected Landsat 8 data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Satellite data", None))
        self.waterVaporGroupBox.setTitle(_translate("Dialog", "Water vapor source", None))
        self.waterVaporMODISRadioButton.setText(_translate("Dialog", "Get automatically by Terra MODIS\n"
"(internet connection and MRTSwath\n"
"needed, takes a LONG time)", None))
        self.waterVaporMODISSettings.setText(_translate("Dialog", "Settings", None))
        self.waterVaporMeanRadioButtonLine.setText(_translate("Dialog", "2", None))
        self.waterVaporGRIDRadioButton.setText(_translate("Dialog", "Water vapor GRID", None))
        self.waterVaporMeanRadioButton.setText(_translate("Dialog", "Manual mean value", None))
        self.waterVaporCheckButton.setText(_translate("Dialog", "Check", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Meteorological data", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Land Surface Emissivity source", None))
        self.LSEGRIDRadioButton.setText(_translate("Dialog", "LSE GRID", None))
        self.LSENDVIRadioButton.setText(_translate("Dialog", "NDVI (Automated)", None))
        self.LSECheckButton.setText(_translate("Dialog", "Check", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Ground data", None))
        self.label_3.setText(_translate("Dialog", "Output land surface temperature (LST) raster:", None))
        self.outputLSTBrowseButton.setText(_translate("Dialog", "Browse", None))
        self.outputLSTCheckButton.setText(_translate("Dialog", "Check", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Output", None))
